server:
  port: 8888

spring:
  application:
    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///C:/DBScertusCicloV/Ecommerce/micro-gestion-config-data
          
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Csvm2021/dsbsV.git
          searchPaths: /ms-gestion-config-data/ms-gestion-config-data/
          username: ${USER_NAME}
          password: ${USER_PASSWORD}
          default-label: main
          cloneOnStart: true
          ignore-local-ssh-settings: true    
